name: Clean Cache

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      cache-key:
        description: 'Cache Key to Clean'
        required: true
        default: "working_dir*"

- uses: actions/setup-node@v2
  with:
    node-version: 14
- name: Install esy
  run: npm install -g esy
- uses: esy/github-action@v1
  with:
    cache-key: ${{ github.event.inputs.ssh }}
